### Creación de Dataframes

A partir de un Diccionario

In [2]:
import pandas as pd

In [3]:
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Marta'],
    'Edad': [28, 34, 22, 45],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla']
}
df = pd.DataFrame(data)
print(df)

   Nombre  Edad     Ciudad
0     Ana    28     Madrid
1    Luis    34  Barcelona
2  Carlos    22   Valencia
3   Marta    45    Sevilla

A partir de una lista

In [5]:
data_lista = [
    ['Ana', 28, 'Madrid'],
    ['Luis', 34, 'Barcelona'],
    ['Carlos', 22, 'Valencia'],
    ['Marta', 45, 'Sevilla']
]

df_lista = pd.DataFrame(data_lista, columns=['Nombre', 'Edad', 'Ciudad'])
print(df_lista)

   Nombre  Edad     Ciudad
0     Ana    28     Madrid
1    Luis    34  Barcelona
2  Carlos    22   Valencia
3   Marta    45    Sevilla

A partir de una lista de diccionarios (Ideal para APIs/JSON)

In [7]:
data_json = [
    {"Nombre": "Ana", "Edad": 28, "Ciudad": "Madrid"},
    {"Nombre": "Luis", "Edad": 34, "Ciudad": "Barcelona"},
    {"Nombre": "Carlos", "Edad": 22, "Ciudad": "Valencia"},
    {"Nombre": "Marta", "Edad": 45, "Ciudad": "Sevilla"}
]
df_json = pd.DataFrame(data_json)
print(df_json)

   Nombre  Edad     Ciudad
0     Ana    28     Madrid
1    Luis    34  Barcelona
2  Carlos    22   Valencia
3   Marta    45    Sevilla

A partir de un diccionario de diccionarios

In [13]:
data_dict_dict = {
    'Nombre': {0: 'Ana', 1: 'Luis', 2: 'Carlos', 3: 'Marta'},
    'Edad': {0: 28, 1: 34, 2: 22, 3: 45},
    'Ciudad': {0: 'Madrid', 1: 'Barcelona', 2: 'Valencia', 3: 'Sevilla'}
}
df_dict_dict = pd.DataFrame(data_dict_dict)
print(df_dict_dict)

   Nombre  Edad     Ciudad
0     Ana    28     Madrid
1    Luis    34  Barcelona
2  Carlos    22   Valencia
3   Marta    45    Sevilla

DataFrame vacío con columnas predefinidas

In [14]:
df_vacio = pd.DataFrame(columns=['Nombre', 'Edad', 'Ciudad'])
print(df_vacio)

Empty DataFrame
Columns: [Nombre, Edad, Ciudad]
Index: []

Dataframe a partir de Series de Pandas

In [15]:
series_nombre = pd.Series(['Ana', 'Luis', 'Carlos', 'Marta'])
series_edad = pd.Series([28, 34, 22, 45])
series_ciudad = pd.Series(['Madrid', 'Barcelona', 'Valencia', 'Sevilla'])
df_series = pd.DataFrame({
    'Nombre': series_nombre,
    'Edad': series_edad,
    'Ciudad': series_ciudad
})
print(df_series)

   Nombre  Edad     Ciudad
0     Ana    28     Madrid
1    Luis    34  Barcelona
2  Carlos    22   Valencia
3   Marta    45    Sevilla

In [16]:
series_nombre = pd.Series(['Ana', 'Luis', 'Carlos', 'Marta'])
series_edad = pd.Series([28, 34, 22, 45])
series_ciudad = pd.Series(['Madrid', 'Barcelona', 'Valencia', 'Sevilla'])
df_series = pd.concat([series_nombre, series_edad, series_ciudad], axis=1) # Concatenar las series como columnas (eso lo indica axis=1)
df_series.columns = ['Nombre', 'Edad', 'Ciudad']
print(df_series)

   Nombre  Edad     Ciudad
0     Ana    28     Madrid
1    Luis    34  Barcelona
2  Carlos    22   Valencia
3   Marta    45    Sevilla

A partir de datos ficticios

In [17]:
num_filas = 10000
df_grande = pd.DataFrame({
    'Nombre': ['Nombre' + str(i) for i in range(num_filas)],
    'Edad': [i % 100 for i in range(num_filas)],
    'Ciudad': ['Ciudad' + str(i % 10) for i in range(num_filas)]
}, index=range(1, num_filas + 1))
print(df_grande)

           Nombre  Edad   Ciudad
1         Nombre0     0  Ciudad0
2         Nombre1     1  Ciudad1
3         Nombre2     2  Ciudad2
4         Nombre3     3  Ciudad3
5         Nombre4     4  Ciudad4
...           ...   ...      ...
9996   Nombre9995    95  Ciudad5
9997   Nombre9996    96  Ciudad6
9998   Nombre9997    97  Ciudad7
9999   Nombre9998    98  Ciudad8
10000  Nombre9999    99  Ciudad9

[10000 rows x 3 columns]

In [18]:
fila_base = pd.DataFrame([{
    'Nombre': 'NombreX',
    'Edad': 25,
    'Ciudad': 'CiudadX'
}])
# Repetir la fila base 10000 veces para crear un DataFrame grande
df_grande_repetido = pd.concat([fila_base] * num_filas, ignore_index=True)
print(df_grande_repetido)

       Nombre  Edad   Ciudad
0     NombreX    25  CiudadX
1     NombreX    25  CiudadX
2     NombreX    25  CiudadX
3     NombreX    25  CiudadX
4     NombreX    25  CiudadX
...       ...   ...      ...
9995  NombreX    25  CiudadX
9996  NombreX    25  CiudadX
9997  NombreX    25  CiudadX
9998  NombreX    25  CiudadX
9999  NombreX    25  CiudadX

[10000 rows x 3 columns]

A partir de un csv

In [ ]:
# Lo más común en un CSV es que la primera fila contenga los nombres de las columnas, por lo que no es necesario especificar el parámetro header. Sin embargo, si el CSV no tiene una fila de encabezado, puedes usar header=None para indicar que la primera fila es parte de los datos.
# Los separadores comunes en un CSV son la coma (,) y el punto y coma (;). Si tu CSV utiliza un separador diferente, asegúrate de especificarlo correctamente con el parámetro sep.
data_csv = pd.read_csv('../data/datos_ficticios.csv', sep=',', encoding='utf-8')
data_csv.head()

,nombre,direccion,correo_electronico,telefono
0,Severiano Muro-Berrocal,"Via de Morena Gonzalo 286, Albacete, 11846",manuelavila@example.org,+34942 546 574
1,Inocencio Salmerón Alfaro,"Cañada de Gaspar Arjona 37, Huelva, 13528",eutropio59@example.com,+34826 14 02 72
2,Alicia Anita Jimenez Taboada,"C. de Chelo Téllez 7, Valladolid, 40342",berta08@example.com,+34 881 969 129
3,Azahara Parejo Barranco,"Avenida de Jose Ramón Pablo 8 Apt. 97 , Soria,...",jimenamorera@example.com,+34885 113 193
4,Graciano Peral Villena,"Acceso Amparo Pallarès 10, Santa Cruz de Tener...",luisina18@example.net,+34 971 233 069

In [ ]:
ruta_fichero = '../data/personajes_sw.csv'
nombre_columnas = ['nombre', 'color_ojos', 'numero_peliculas']
data_sw = pd.read_csv(ruta_fichero, sep=',', encoding='utf-8', header=None, names=nombre_columnas)
data_sw.head()

           nombre color_ojos  numero_peliculas
0  Luke Skywalker       blue                 4
1           C-3PO     yellow                 6
2           R2-D2        red                 6
3     Darth Vader     yellow                 4
4     Leia Organa      brown                 4

A partir de un txt (se trabaja como si fuese un csv)

In [30]:
df_txt = pd.read_csv('../data/fichero.txt', sep='\t', encoding='utf-8', header=None, names=['Nombre','Edad'])
df_txt.head()

  Nombre  Edad
0   Fran    49
1   Dani    46
2   Paco    75

A partir del portapapeles (Ctrl + C)

In [32]:
df_portapapeles = pd.read_clipboard(sep=",")
print(df_portapapeles)

                             nombre  \
0           Severiano Muro-Berrocal
1         Inocencio Salmerón Alfaro
2      Alicia Anita Jimenez Taboada
3           Azahara Parejo Barranco
4            Graciano Peral Villena
5             Leonor del Torrecilla
6              Elpidio Nuñez Abella
7             Plácido Salcedo Bayón
8            Augusto Cárdenas Peñas
9                       Reyes Ariza
10            Alejandro Perales-Amo
11  Ángel Eleuterio Reina Hernandez

                                            direccion  \
0          Via de Morena Gonzalo 286, Albacete, 11846
1           Cañada de Gaspar Arjona 37, Huelva, 13528
2             C. de Chelo Téllez 7, Valladolid, 40342
3   Avenida de Jose Ramón Pablo 8 Apt. 97 , Soria,...
4   Acceso Amparo Pallarès 10, Santa Cruz de Tener...
5           Plaza Mireia Ortuño 2, Guadalajara, 45576
6   Cañada Demetrio Guillén 40 Apt. 96 , Pontevedr...
7   Urbanización de Visitación Jerez 5 Puerta 7 , ...
8        Paseo Eloy Perez 74 Puerta 6 , Huesca, 18131
9     Pasadizo María Pilar Carbonell 1, Cuenca, 27253
10               Cuesta Danilo Román 37, Ávila, 41074
11    Acceso Lina Arribas 12 Piso 3 , Asturias, 15225

                 correo_electronico         telefono
0           manuelavila@example.org   +34942 546 574
1            eutropio59@example.com  +34826 14 02 72
2               berta08@example.com  +34 881 969 129
3          jimenamorera@example.com   +34885 113 193
4             luisina18@example.net  +34 971 233 069
5   concepcioncarretero@example.com  +34 871 281 010
6              qdomingo@example.net    +34 977184126
7               diana20@example.net   +34821 847 329
8               rpinedo@example.com    +34 927936850
9                mvidal@example.net  +34857 35 74 97
10          maricebrian@example.com     +34874590645
11               nbanos@example.org  +34 942 220 225

In [33]:
df_excel = pd.read_excel('../data/datos_excel.xlsx', sheet_name='Datos')
df_excel.head()

  Nombre  Edad
0   Fran    49
1   Dani    46
2   Paco    75

A partir de una url

In [ ]:
url_base = 'https://jsonplaceholder.typicode.com/posts'
df_api = pd.read_json(url_base)
df_api.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

A partir de un html

In [49]:
import pandas as pd
import requests
from io import StringIO

url_base = 'https://es.wikipedia.org/wiki/Anexo:Países'

# 1. Definimos un User-Agent simulando ser el navegador Google Chrome en Windows
cabeceras = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}

# 2. Hacemos la petición incluyendo las cabeceras
respuesta = requests.get(url_base, headers=cabeceras)

# 3. Verificamos que Wikipedia nos ha dado acceso (el código 200 significa "OK")
if respuesta.status_code == 200:
    # Le pasamos el texto HTML a pandas usando StringIO
    df_wikipedia = pd.read_html(StringIO(respuesta.text))
    
    # Extraemos nuestra tabla. A veces en Wikipedia la tabla principal no es la 0,
    # pero en este artículo específico suele ser la primera [0] o la segunda [1].
    paises = df_wikipedia[0]
    
    
else:
    print(f"Error al acceder a la página. Código: {respuesta.status_code}")
paises.head()

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía,Ubicación
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida,NaN
1,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,NaN
2,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida,NaN
3,República de Albania (Albania),República de Albania (Albania),-,-,-,-,-,NaN
4,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida,NaN

In [50]:
paises.tail()

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía,Ubicación
385,República de Yibuti (Yibuti),República de Yibuti (Yibuti),Yibuti mantiene un conflicto fronterizo con Er...,Yibuti mantiene un conflicto fronterizo con Er...,Yibuti mantiene un conflicto fronterizo con Er...,Yibuti mantiene un conflicto fronterizo con Er...,Yibuti mantiene un conflicto fronterizo con Er...,NaN
386,República de Zambia (Zambia),República de Zambia (Zambia),República presidencial,Lusaka,África,Miembro (1964),Reconocida,NaN
387,República de Zambia (Zambia),República de Zambia (Zambia),-,-,-,-,-,NaN
388,República de Zimbabue (Zimbabue),República de Zimbabue (Zimbabue),República presidencial,Harare -,África,Miembro (1980),Reconocida,NaN
389,República de Zimbabue (Zimbabue),República de Zimbabue (Zimbabue),-,-,-,-,-,NaN

In [51]:
paises.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 8 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Estado soberano (nombre común)    390 non-null    object
 1   Estado soberano (nombre común).1  390 non-null    object
 2   Forma de gobierno                 389 non-null    object
 3   Capital(es)                       389 non-null    object
 4   Continente                        389 non-null    object
 5   Estatus ONU                       389 non-null    object
 6   Soberanía                         389 non-null    object
 7   Ubicación                         0 non-null      float64
dtypes: float64(1), object(7)
memory usage: 24.5+ KB

A partir de una base de datos

Si cogemos la tabla entera

In [53]:
# SQL (Desde cualquier base de datos con un conector compatible, como MySQL, PostgreSQL, SQLite, etc.)
# Requiere: pip install sqlalchemy
from sqlalchemy import create_engine

In [54]:
username = 'root'
password = ''
host = 'localhost'
dbname = 'futbol'
engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}/{dbname}')  # Reemplaza con tu cadena de conexión
df_sql_table = pd.read_sql_table('equipos', con=engine)  # Reemplaza 'equipos' con el nombre real de tu tabla
df_sql_table.head()

,id_equipo,nombre,nombre_corto,tla,fundacion,estadio
0,3,Bayer 04 Leverkusen,Leverkusen,B04,1904.0,BayArena
1,4,Borussia Dortmund,Dortmund,BVB,1909.0,Signal Iduna Park
2,5,FC Bayern Munich,Bayern,FCB,1900.0,Allianz Arena
3,19,Eintracht Frankfurt,Frankfurt,SGE,1899.0,Deutsche Bank Park
4,57,Arsenal FC,Arsenal,ARS,1886.0,Emirates Stadium

In [56]:
df_sql_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_equipo     83 non-null     int64
 1   nombre        83 non-null     object
 2   nombre_corto  83 non-null     object
 3   tla           83 non-null     object
 4   fundacion     79 non-null     float64
 5   estadio       82 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.0+ KB

In [59]:
df_sql_table.describe()

          id_equipo    fundacion
count     83.000000    79.000000
mean    1690.144578  1916.012658
std     2723.142827    22.263857
min        3.000000  1880.000000
25%       91.000000  1902.000000
50%      610.000000  1910.000000
75%     1462.500000  1923.500000
max    11034.000000  1992.000000

A partir de una SQL

In [60]:
username = 'root'
password = ''
host = 'localhost'
dbname = 'futbol'
engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}/{dbname}')  # Reemplaza con tu cadena de conexión
df_sql = pd.read_sql('SELECT * FROM equipos WHERE fundacion > 1950', con=engine)  # Reemplaza 'equipos' con el nombre real de tu tabla
df_sql.head()

,id_equipo,nombre,nombre_corto,tla,fundacion,estadio
0,611,Qarabağ Ağdam FK,Qarabağ Ağdam,QAR,1951,Tofiq Bəhramov adına Respublika stadionu
1,666,FC Twente '65,Twente,TWE,1965,De Grolsch Veste
2,676,FC Utrecht,Utrecht,UTR,1970,Stadion Galgenwaard
3,682,AZ,AZ,AZ,1967,AFAS Stadion
4,712,FC Arouca,Arouca,FCA,1952,Estádio Municipal de Arouca

In [61]:
df_sql.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_equipo     8 non-null      int64
 1   nombre        8 non-null      object
 2   nombre_corto  8 non-null      object
 3   tla           8 non-null      object
 4   fundacion     8 non-null      int64
 5   estadio       8 non-null      object
dtypes: int64(2), object(4)
memory usage: 516.0+ bytes

A partir de un archivo pickle (formato binario típico en Python)

In [64]:
data_pickle = pd.read_pickle('../data/backup_equipos.pkl')
data_pickle.head()

,id_equipo,nombre,nombre_corto,tla,fundacion,estadio
0,611,Qarabağ Ağdam FK,Qarabağ Ağdam,QAR,1951,Tofiq Bəhramov adına Respublika stadionu
1,666,FC Twente '65,Twente,TWE,1965,De Grolsch Veste
2,676,FC Utrecht,Utrecht,UTR,1970,Stadion Galgenwaard
3,682,AZ,AZ,AZ,1967,AFAS Stadion
4,712,FC Arouca,Arouca,FCA,1952,Estádio Municipal de Arouca

### Guardar Dataframes en archivos

In [ ]:
# Realizar copia de seguridad de un dataframe a un nuevo archivo CSV
df_sql.to_csv('../data/backup_equipos.csv', index=False)

In [66]:
# Guardar copia de seguridad como pickle (formato binario específico de Python para objetos)
df_sql.to_pickle('../data/backup_equipos.pkl')