In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Primero cargo el dataset en un DataFrame

In [3]:
df = pd.read_csv('../data/paises.csv', header="infer", encoding="utf-8")
df.head()

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía,Ubicación
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida,NaN
1,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,NaN
2,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida,NaN
3,República de Albania (Albania),República de Albania (Albania),-,-,-,-,-,NaN
4,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 8 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Estado soberano (nombre común)    390 non-null    object
 1   Estado soberano (nombre común).1  390 non-null    object
 2   Forma de gobierno                 389 non-null    object
 3   Capital(es)                       389 non-null    object
 4   Continente                        389 non-null    object
 5   Estatus ONU                       389 non-null    object
 6   Soberanía                         389 non-null    object
 7   Ubicación                         0 non-null      float64
dtypes: float64(1), object(7)
memory usage: 24.5+ KB

Eliminar una columna

In [ ]:
df.drop(columns=['Ubicación']).head() # Elimina la columna 'Ubicación' pero NO MODIFICA el DataFrame original y muestra las primeras filas del DataFrame resultante.

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida
1,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...
2,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida
3,República de Albania (Albania),República de Albania (Albania),-,-,-,-,-
4,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida

In [6]:
df.head()

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía,Ubicación
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida,NaN
1,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,NaN
2,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida,NaN
3,República de Albania (Albania),República de Albania (Albania),-,-,-,-,-,NaN
4,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida,NaN

In [7]:
df_sin_ubicacion = df.drop(columns=['Ubicación']) # Elimina la columna 'Ubicación' y guarda el resultado en un nuevo DataFrame llamado df_sin_ubicacion.
df_sin_ubicacion.head()

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida
1,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...
2,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida
3,República de Albania (Albania),República de Albania (Albania),-,-,-,-,-
4,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida

Eliminación de columnas sobre el propio DataFrame

In [8]:
df.drop(columns=['Ubicación'], inplace=True) # Elimina la columna 'Ubicación' del DataFrame original df y modifica el DataFrame original.
df.head()

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida
1,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...
2,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida
3,República de Albania (Albania),República de Albania (Albania),-,-,-,-,-
4,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida

In [12]:
# Eliminar filas impares del Dataframe
df.drop(index=df.index[1::2], axis=0, inplace=True) # Elimina las filas con índices impares del DataFrame df_sin_ubicacion y modifica el DataFrame original.
df.head()

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida
2,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida
4,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida
6,Principado de Andorra (Andorra),Principado de Andorra (Andorra),Monarquía constitucional,Andorra la Vieja,Europa,Miembro (1993),Reconocida
8,República de Angola (Angola),República de Angola (Angola),República presidencialista,Luanda,África,Miembro (1976),Reconocida

In [13]:
df.to_csv('../data/paises_limpios.csv', index=False) # Guarda el DataFrame df_sin_ubicacion en un nuevo archivo CSV llamado 'paises_limpios.csv' sin incluir los índices de las filas.

Seleccionar filas

In [16]:
df_indices = df.iloc[0:10] # Crea un nuevo DataFrame llamado df_indices que contiene las primeras 10 filas del DataFrame df utilizando la función iloc para seleccionar las filas por su posición.
df_indices

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida
2,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida
4,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida
6,Principado de Andorra (Andorra),Principado de Andorra (Andorra),Monarquía constitucional,Andorra la Vieja,Europa,Miembro (1993),Reconocida
8,República de Angola (Angola),República de Angola (Angola),República presidencialista,Luanda,África,Miembro (1976),Reconocida
10,Antigua y Barbuda,Antigua y Barbuda,Monarquía constitucional,Saint John,América,Miembro (1981),Reconocida
12,Reino de Arabia Saudita (Arabia Saudita/Arabia...,Reino de Arabia Saudita (Arabia Saudita/Arabia...,Monarquía absoluta,Riad,Asia,Miembro (1945),Reconocida
14,República Argelina Democrática y Popular (Arge...,República Argelina Democrática y Popular (Arge...,República semipresidencialista,Argel,África,Miembro (1962),Reconocida
16,República Argentina (Argentina),República Argentina (Argentina),República presidencialista,Buenos Aires,América,Miembro (1945),Reconocida
18,República de Armenia (Armenia),República de Armenia (Armenia),República parlamentaria,Ereván,Asia-Europa,Miembro (1992),Reconocida

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 388
Data columns (total 7 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Estado soberano (nombre común)    195 non-null    object
 1   Estado soberano (nombre común).1  195 non-null    object
 2   Forma de gobierno                 195 non-null    object
 3   Capital(es)                       195 non-null    object
 4   Continente                        195 non-null    object
 5   Estatus ONU                       195 non-null    object
 6   Soberanía                         195 non-null    object
dtypes: object(7)
memory usage: 10.8+ KB