### Creación de Dataframes

A partir de un Diccionario

In [2]:
import pandas as pd

In [3]:
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Marta'],
    'Edad': [28, 34, 22, 45],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Sevilla']
}
df = pd.DataFrame(data)
print(df)

   Nombre  Edad     Ciudad
0     Ana    28     Madrid
1    Luis    34  Barcelona
2  Carlos    22   Valencia
3   Marta    45    Sevilla

A partir de una lista

In [5]:
data_lista = [
    ['Ana', 28, 'Madrid'],
    ['Luis', 34, 'Barcelona'],
    ['Carlos', 22, 'Valencia'],
    ['Marta', 45, 'Sevilla']
]

df_lista = pd.DataFrame(data_lista, columns=['Nombre', 'Edad', 'Ciudad'])
print(df_lista)

   Nombre  Edad     Ciudad
0     Ana    28     Madrid
1    Luis    34  Barcelona
2  Carlos    22   Valencia
3   Marta    45    Sevilla

A partir de una lista de diccionarios (Ideal para APIs/JSON)

In [7]:
data_json = [
    {"Nombre": "Ana", "Edad": 28, "Ciudad": "Madrid"},
    {"Nombre": "Luis", "Edad": 34, "Ciudad": "Barcelona"},
    {"Nombre": "Carlos", "Edad": 22, "Ciudad": "Valencia"},
    {"Nombre": "Marta", "Edad": 45, "Ciudad": "Sevilla"}
]
df_json = pd.DataFrame(data_json)
print(df_json)

   Nombre  Edad     Ciudad
0     Ana    28     Madrid
1    Luis    34  Barcelona
2  Carlos    22   Valencia
3   Marta    45    Sevilla

A partir de un diccionario de diccionarios

In [13]:
data_dict_dict = {
    'Nombre': {0: 'Ana', 1: 'Luis', 2: 'Carlos', 3: 'Marta'},
    'Edad': {0: 28, 1: 34, 2: 22, 3: 45},
    'Ciudad': {0: 'Madrid', 1: 'Barcelona', 2: 'Valencia', 3: 'Sevilla'}
}
df_dict_dict = pd.DataFrame(data_dict_dict)
print(df_dict_dict)

   Nombre  Edad     Ciudad
0     Ana    28     Madrid
1    Luis    34  Barcelona
2  Carlos    22   Valencia
3   Marta    45    Sevilla

DataFrame vacío con columnas predefinidas

In [14]:
df_vacio = pd.DataFrame(columns=['Nombre', 'Edad', 'Ciudad'])
print(df_vacio)

Empty DataFrame
Columns: [Nombre, Edad, Ciudad]
Index: []

Dataframe a partir de Series de Pandas

In [15]:
series_nombre = pd.Series(['Ana', 'Luis', 'Carlos', 'Marta'])
series_edad = pd.Series([28, 34, 22, 45])
series_ciudad = pd.Series(['Madrid', 'Barcelona', 'Valencia', 'Sevilla'])
df_series = pd.DataFrame({
    'Nombre': series_nombre,
    'Edad': series_edad,
    'Ciudad': series_ciudad
})
print(df_series)

   Nombre  Edad     Ciudad
0     Ana    28     Madrid
1    Luis    34  Barcelona
2  Carlos    22   Valencia
3   Marta    45    Sevilla

In [16]:
series_nombre = pd.Series(['Ana', 'Luis', 'Carlos', 'Marta'])
series_edad = pd.Series([28, 34, 22, 45])
series_ciudad = pd.Series(['Madrid', 'Barcelona', 'Valencia', 'Sevilla'])
df_series = pd.concat([series_nombre, series_edad, series_ciudad], axis=1) # Concatenar las series como columnas (eso lo indica axis=1)
df_series.columns = ['Nombre', 'Edad', 'Ciudad']
print(df_series)

   Nombre  Edad     Ciudad
0     Ana    28     Madrid
1    Luis    34  Barcelona
2  Carlos    22   Valencia
3   Marta    45    Sevilla

A partir de datos ficticios

In [17]:
num_filas = 10000
df_grande = pd.DataFrame({
    'Nombre': ['Nombre' + str(i) for i in range(num_filas)],
    'Edad': [i % 100 for i in range(num_filas)],
    'Ciudad': ['Ciudad' + str(i % 10) for i in range(num_filas)]
}, index=range(1, num_filas + 1))
print(df_grande)

           Nombre  Edad   Ciudad
1         Nombre0     0  Ciudad0
2         Nombre1     1  Ciudad1
3         Nombre2     2  Ciudad2
4         Nombre3     3  Ciudad3
5         Nombre4     4  Ciudad4
...           ...   ...      ...
9996   Nombre9995    95  Ciudad5
9997   Nombre9996    96  Ciudad6
9998   Nombre9997    97  Ciudad7
9999   Nombre9998    98  Ciudad8
10000  Nombre9999    99  Ciudad9

[10000 rows x 3 columns]

In [18]:
fila_base = pd.DataFrame([{
    'Nombre': 'NombreX',
    'Edad': 25,
    'Ciudad': 'CiudadX'
}])
# Repetir la fila base 10000 veces para crear un DataFrame grande
df_grande_repetido = pd.concat([fila_base] * num_filas, ignore_index=True)
print(df_grande_repetido)

       Nombre  Edad   Ciudad
0     NombreX    25  CiudadX
1     NombreX    25  CiudadX
2     NombreX    25  CiudadX
3     NombreX    25  CiudadX
4     NombreX    25  CiudadX
...       ...   ...      ...
9995  NombreX    25  CiudadX
9996  NombreX    25  CiudadX
9997  NombreX    25  CiudadX
9998  NombreX    25  CiudadX
9999  NombreX    25  CiudadX

[10000 rows x 3 columns]

A partir de un csv

In [ ]:
# Lo más común en un CSV es que la primera fila contenga los nombres de las columnas, por lo que no es necesario especificar el parámetro header. Sin embargo, si el CSV no tiene una fila de encabezado, puedes usar header=None para indicar que la primera fila es parte de los datos.
# Los separadores comunes en un CSV son la coma (,) y el punto y coma (;). Si tu CSV utiliza un separador diferente, asegúrate de especificarlo correctamente con el parámetro sep.
data_csv = pd.read_csv('../data/datos_ficticios.csv', sep=',', encoding='utf-8')
data_csv.head()

,nombre,direccion,correo_electronico,telefono
0,Severiano Muro-Berrocal,"Via de Morena Gonzalo 286, Albacete, 11846",manuelavila@example.org,+34942 546 574
1,Inocencio Salmerón Alfaro,"Cañada de Gaspar Arjona 37, Huelva, 13528",eutropio59@example.com,+34826 14 02 72
2,Alicia Anita Jimenez Taboada,"C. de Chelo Téllez 7, Valladolid, 40342",berta08@example.com,+34 881 969 129
3,Azahara Parejo Barranco,"Avenida de Jose Ramón Pablo 8 Apt. 97 , Soria,...",jimenamorera@example.com,+34885 113 193
4,Graciano Peral Villena,"Acceso Amparo Pallarès 10, Santa Cruz de Tener...",luisina18@example.net,+34 971 233 069

In [ ]:
ruta_fichero = '../data/personajes_sw.csv'
nombre_columnas = ['nombre', 'color_ojos', 'numero_peliculas']
data_sw = pd.read_csv(ruta_fichero, sep=',', encoding='utf-8', header=None, names=nombre_columnas)
data_sw.head()

           nombre color_ojos  numero_peliculas
0  Luke Skywalker       blue                 4
1           C-3PO     yellow                 6
2           R2-D2        red                 6
3     Darth Vader     yellow                 4
4     Leia Organa      brown                 4