In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Primero cargo el dataset en un DataFrame

In [3]:
df = pd.read_csv('../data/paises.csv', header="infer", encoding="utf-8")
df.head()

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía,Ubicación
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida,NaN
1,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,NaN
2,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida,NaN
3,República de Albania (Albania),República de Albania (Albania),-,-,-,-,-,NaN
4,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 8 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Estado soberano (nombre común)    390 non-null    object
 1   Estado soberano (nombre común).1  390 non-null    object
 2   Forma de gobierno                 389 non-null    object
 3   Capital(es)                       389 non-null    object
 4   Continente                        389 non-null    object
 5   Estatus ONU                       389 non-null    object
 6   Soberanía                         389 non-null    object
 7   Ubicación                         0 non-null      float64
dtypes: float64(1), object(7)
memory usage: 24.5+ KB

Eliminar una columna

In [ ]:
df.drop(columns=['Ubicación']).head() # Elimina la columna 'Ubicación' pero NO MODIFICA el DataFrame original y muestra las primeras filas del DataFrame resultante.

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida
1,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...
2,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida
3,República de Albania (Albania),República de Albania (Albania),-,-,-,-,-
4,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida

In [6]:
df.head()

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía,Ubicación
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida,NaN
1,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,NaN
2,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida,NaN
3,República de Albania (Albania),República de Albania (Albania),-,-,-,-,-,NaN
4,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida,NaN

In [7]:
df_sin_ubicacion = df.drop(columns=['Ubicación']) # Elimina la columna 'Ubicación' y guarda el resultado en un nuevo DataFrame llamado df_sin_ubicacion.
df_sin_ubicacion.head()

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida
1,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...
2,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida
3,República de Albania (Albania),República de Albania (Albania),-,-,-,-,-
4,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida

Eliminación de columnas sobre el propio DataFrame

In [8]:
df.drop(columns=['Ubicación'], inplace=True) # Elimina la columna 'Ubicación' del DataFrame original df y modifica el DataFrame original.
df.head()

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida
1,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...,Las Naciones Unidas actualmente reconocen a la...
2,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida
3,República de Albania (Albania),República de Albania (Albania),-,-,-,-,-
4,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida

In [12]:
# Eliminar filas impares del Dataframe
df.drop(index=df.index[1::2], axis=0, inplace=True) # Elimina las filas con índices impares del DataFrame df_sin_ubicacion y modifica el DataFrame original.
df.head()

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida
2,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida
4,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida
6,Principado de Andorra (Andorra),Principado de Andorra (Andorra),Monarquía constitucional,Andorra la Vieja,Europa,Miembro (1993),Reconocida
8,República de Angola (Angola),República de Angola (Angola),República presidencialista,Luanda,África,Miembro (1976),Reconocida

In [ ]:
df.to_csv('../data/paises_limpios.csv', index=False) # Guarda el DataFrame df_sin_ubicacion en un nuevo archivo CSV llamado 'paises_limpios.csv' sin incluir los índices de las filas.

Seleccionar filas

In [16]:
df_indices = df.iloc[0:10] # Crea un nuevo DataFrame llamado df_indices que contiene las primeras 10 filas del DataFrame df utilizando la función iloc para seleccionar las filas por su posición.
df_indices

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida
2,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida
4,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida
6,Principado de Andorra (Andorra),Principado de Andorra (Andorra),Monarquía constitucional,Andorra la Vieja,Europa,Miembro (1993),Reconocida
8,República de Angola (Angola),República de Angola (Angola),República presidencialista,Luanda,África,Miembro (1976),Reconocida
10,Antigua y Barbuda,Antigua y Barbuda,Monarquía constitucional,Saint John,América,Miembro (1981),Reconocida
12,Reino de Arabia Saudita (Arabia Saudita/Arabia...,Reino de Arabia Saudita (Arabia Saudita/Arabia...,Monarquía absoluta,Riad,Asia,Miembro (1945),Reconocida
14,República Argelina Democrática y Popular (Arge...,República Argelina Democrática y Popular (Arge...,República semipresidencialista,Argel,África,Miembro (1962),Reconocida
16,República Argentina (Argentina),República Argentina (Argentina),República presidencialista,Buenos Aires,América,Miembro (1945),Reconocida
18,República de Armenia (Armenia),República de Armenia (Armenia),República parlamentaria,Ereván,Asia-Europa,Miembro (1992),Reconocida

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 388
Data columns (total 7 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Estado soberano (nombre común)    195 non-null    object
 1   Estado soberano (nombre común).1  195 non-null    object
 2   Forma de gobierno                 195 non-null    object
 3   Capital(es)                       195 non-null    object
 4   Continente                        195 non-null    object
 5   Estatus ONU                       195 non-null    object
 6   Soberanía                         195 non-null    object
dtypes: object(7)
memory usage: 10.8+ KB

In [3]:
df_paises = pd.read_csv('../data/paises_limpios.csv', header="infer", encoding="utf-8") # Lee el archivo CSV 'paises_limpios.csv' y lo carga en un nuevo DataFrame llamado df_paises.
df_paises.head()

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida
1,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida
2,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida
3,Principado de Andorra (Andorra),Principado de Andorra (Andorra),Monarquía constitucional,Andorra la Vieja,Europa,Miembro (1993),Reconocida
4,República de Angola (Angola),República de Angola (Angola),República presidencialista,Luanda,África,Miembro (1976),Reconocida

In [4]:
df_paises.reset_index(drop=True, inplace=True) # Restablece los índices del DataFrame df_paises, eliminando los índices anteriores y creando nuevos índices secuenciales. El parámetro drop=True evita que los índices anteriores se agreguen como una nueva columna en el DataFrame.
df_paises.head()

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida
1,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida
2,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida
3,Principado de Andorra (Andorra),Principado de Andorra (Andorra),Monarquía constitucional,Andorra la Vieja,Europa,Miembro (1993),Reconocida
4,República de Angola (Angola),República de Angola (Angola),República presidencialista,Luanda,África,Miembro (1976),Reconocida

In [6]:
df_paises.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 7 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Estado soberano (nombre común)    195 non-null    object
 1   Estado soberano (nombre común).1  195 non-null    object
 2   Forma de gobierno                 195 non-null    object
 3   Capital(es)                       195 non-null    object
 4   Continente                        195 non-null    object
 5   Estatus ONU                       195 non-null    object
 6   Soberanía                         195 non-null    object
dtypes: object(7)
memory usage: 10.8+ KB

In [ ]:
type(df_paises) # Muestra el tipo de objeto del DataFrame df_paises, que es <class 'pandas.core.frame.DataFrame'>.

pandas.core.frame.DataFrame

Consultar datos y crear vistas parciales

In [9]:
df_parcial = df_paises[['Estado soberano (nombre común)', 'Continente']] # Crea un nuevo DataFrame llamado df_parcial que contiene solo las columnas 'Estado soberano (nombre común)' y 'Continente' del DataFrame df.
df_parcial.head()

                Estado soberano (nombre común) Continente
0  Emirato Islámico de Afganistán (Afganistán)       Asia
1               República de Albania (Albania)     Europa
2     República Federal de Alemania (Alemania)     Europa
3              Principado de Andorra (Andorra)     Europa
4                 República de Angola (Angola)     África

In [10]:
df_parcial.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 2 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Estado soberano (nombre común)  195 non-null    object
 1   Continente                      195 non-null    object
dtypes: object(2)
memory usage: 3.2+ KB

In [12]:
df_parcial_100 = df_paises.loc[:99, ['Estado soberano (nombre común)', 'Continente']] # Crea un nuevo DataFrame llamado df_parcial_100 que contiene las primeras 100 filas y solo las columnas 'Estado soberano (nombre común)' y 'Continente' del DataFrame df_paises utilizando la función loc para seleccionar las filas por su etiqueta.
df_parcial_100.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Estado soberano (nombre común)  100 non-null    object
 1   Continente                      100 non-null    object
dtypes: object(2)
memory usage: 1.7+ KB

In [13]:
df_basado_indices = df_paises.iloc[:100, [0, 1, 2, 5]] # Crea un nuevo DataFrame llamado df_basado_indices que contiene las primeras 100 filas y solo las columnas en las posiciones 0 y 1, 2, 5 del DataFrame df_paises utilizando la función iloc para seleccionar las filas por su posición.
df_basado_indices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Estado soberano (nombre común)    100 non-null    object
 1   Estado soberano (nombre común).1  100 non-null    object
 2   Forma de gobierno                 100 non-null    object
 3   Estatus ONU                       100 non-null    object
dtypes: object(4)
memory usage: 3.3+ KB

Quedarme con los datos de una fila

In [17]:
albania = df_paises.iloc[1] # Selecciona la fila con índice 1 del DataFrame df y la guarda en una variable llamada albania.
albania # es una Serie de Pandas que contiene los datos de la fila seleccionada, con el índice de cada columna como etiqueta y el valor correspondiente a esa fila.

Estado soberano (nombre común)      República de Albania (Albania)
Estado soberano (nombre común).1    República de Albania (Albania)
Forma de gobierno                          República parlamentaria
Capital(es)                                                 Tirana
Continente                                                  Europa
Estatus ONU                                         Miembro (1955)
Soberanía                                               Reconocida
Name: 1, dtype: object

In [19]:
albania2 = df_paises[df_paises['Estado soberano (nombre común)'] == 'República de Albania (Albania)'] # Selecciona la fila del DataFrame df_paises donde la columna 'Estado soberano (nombre común)' es igual a 'Albania' y guarda el resultado en una variable llamada albania2.
albania2 # es un DataFrame que contiene la fila seleccionada, con el índice de esa fila como etiqueta y las columnas del DataFrame original como etiquetas de columna.

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía
1,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida

In [22]:
republicas_europeas = df_paises[(df_paises['Forma de gobierno'] == 'República parlamentaria') & (df_paises['Continente'] == 'Europa')] # Crea un nuevo DataFrame llamado republicas_europeas que contiene solo las filas del DataFrame df_paises donde la columna 'Tipo de gobierno' es igual a 'República parlamentaria' y la columna 'Continente' es igual a 'Europa'.
republicas_europeas.reset_index(drop=True, inplace=True) # Restablece los índices del DataFrame republicas_europeas, eliminando los índices anteriores y creando nuevos índices secuenciales. El parámetro drop=True evita que los índices anteriores se agreguen como una nueva columna en el DataFrame.
republicas_europeas.head()

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía
0,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida
1,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida
2,República de Austria (Austria),República de Austria (Austria),República parlamentaria,Viena,Europa,Miembro (1955),Reconocida
3,Bosnia y Herzegovina (Bosnia y Herzegovina/Bos...,Bosnia y Herzegovina (Bosnia y Herzegovina/Bos...,República parlamentaria,Sarajevo,Europa,Miembro (1992),Reconocida
4,República de Bulgaria (Bulgaria),República de Bulgaria (Bulgaria),República parlamentaria,Sofía,Europa,Miembro (1955),Reconocida

In [23]:
republicas_europeas_africanas = df_paises[(df_paises['Forma de gobierno'] == 'República parlamentaria') & (df_paises['Continente'].isin(['Europa', 'África']))] # Crea un nuevo DataFrame llamado republicas_europeas_africanas que contiene solo las filas del DataFrame df_paises donde la columna 'Forma de gobierno' es igual a 'República parlamentaria' y la columna 'Continente' está en la lista ['Europa', 'África'].
republicas_europeas_africanas.reset_index(drop=True, inplace=True) # Restablece los índices del DataFrame republicas_europeas_africanas, eliminando los índices anteriores y creando nuevos índices secuenciales. El parámetro drop=True evita que los índices anteriores se agreguen como una nueva columna en el DataFrame.
republicas_europeas_africanas.head()

,Estado soberano (nombre común),Estado soberano (nombre común).1,Forma de gobierno,Capital(es),Continente,Estatus ONU,Soberanía
0,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida
1,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida
2,República de Austria (Austria),República de Austria (Austria),República parlamentaria,Viena,Europa,Miembro (1955),Reconocida
3,Bosnia y Herzegovina (Bosnia y Herzegovina/Bos...,Bosnia y Herzegovina (Bosnia y Herzegovina/Bos...,República parlamentaria,Sarajevo,Europa,Miembro (1992),Reconocida
4,República de Botsuana (Botsuana),República de Botsuana (Botsuana),República parlamentaria,Gaborone,África,Miembro (1966),Reconocida

Renombrar columnas

In [24]:
df_paises = df_paises.rename(columns={'Estado soberano (nombre común)': 'Pais','Estado soberano (nombre común).1': 'Pais_2','Forma de gobierno': 'Gobierno'}) # Cambia el nombre de las columnas 'Estado soberano (nombre común)' a 'Pais' y 'Forma de gobierno' a 'Gobierno' en el DataFrame df_paises.
df_paises.head()

,Pais,Pais_2,Gobierno,Capital(es),Continente,Estatus ONU,Soberanía
0,Emirato Islámico de Afganistán (Afganistán),Emirato Islámico de Afganistán (Afganistán),Emirato islámico,Kabul,Asia,Miembro (1946),Reconocida
1,República de Albania (Albania),República de Albania (Albania),República parlamentaria,Tirana,Europa,Miembro (1955),Reconocida
2,República Federal de Alemania (Alemania),República Federal de Alemania (Alemania),República parlamentaria,Berlín,Europa,Miembro (1973)[1]​,Reconocida
3,Principado de Andorra (Andorra),Principado de Andorra (Andorra),Monarquía constitucional,Andorra la Vieja,Europa,Miembro (1993),Reconocida
4,República de Angola (Angola),República de Angola (Angola),República presidencialista,Luanda,África,Miembro (1976),Reconocida

In [28]:
df_personas = pd.DataFrame({'Nombre': ['Alice', 'Bob', 'Charlie', 'Fran', 'Dani'], 'Edad': [25, 30, np.nan, 40, 45], 'Ciudad': ['Madrid', np.nan, 'Valencia', 'Sevilla', 'Bilbao'], 'Sexo': ['Femenino', 'Masculino', 'Masculino', np.nan, 'Masculino'], 'Altura': [165, np.nan, 175, 170, 185], 'Peso': [55, 70, np.nan, 60, 75]}) # Crea un nuevo DataFrame llamado df_personas con cinco columnas: 'Nombre', 'Edad', 'Ciudad', 'Sexo' y 'Altura', y tres filas de datos correspondientes a cada persona.
df_personas.head()

    Nombre  Edad    Ciudad       Sexo  Altura  Peso
0    Alice  25.0    Madrid   Femenino   165.0  55.0
1      Bob  30.0       NaN  Masculino     NaN  70.0
2  Charlie   NaN  Valencia  Masculino   175.0   NaN
3     Fran  40.0   Sevilla        NaN   170.0  60.0
4     Dani  45.0    Bilbao  Masculino   185.0  75.0

In [29]:
df_personas.describe()

            Edad      Altura       Peso
count   4.000000    4.000000   4.000000
mean   35.000000  173.750000  65.000000
std     9.128709    8.539126   9.128709
min    25.000000  165.000000  55.000000
25%    28.750000  168.750000  58.750000
50%    35.000000  172.500000  65.000000
75%    41.250000  177.500000  71.250000
max    45.000000  185.000000  75.000000

In [30]:
df_personas['Alto_booleano'] = df_personas['Altura'] >= 180 # Crea una nueva columna llamada 'Alto' en el DataFrame df_personas que contiene valores booleanos (True o False) dependiendo de si la altura de cada persona es mayor a 180 cm.
df_personas['Alto_texto'] = np.where(df_personas['Altura'] >= 180, 'Sí', 'No') # Crea una nueva columna llamada 'Alto_texto' en el DataFrame df_personas que contiene valores de texto ('Sí' o 'No') dependiendo de si la altura de cada persona es mayor a 180 cm.
df_personas.head()

    Nombre  Edad    Ciudad       Sexo  Altura  Peso  Alto_booleano Alto_texto
0    Alice  25.0    Madrid   Femenino   165.0  55.0          False         No
1      Bob  30.0       NaN  Masculino     NaN  70.0          False         No
2  Charlie   NaN  Valencia  Masculino   175.0   NaN          False         No
3     Fran  40.0   Sevilla        NaN   170.0  60.0          False         No
4     Dani  45.0    Bilbao  Masculino   185.0  75.0           True         Sí

Agrupaciones y agregaciones

In [31]:
pesos_por_sexo = df_personas.groupby('Sexo')['Peso'].sum().reset_index() # Agrupa el DataFrame df_personas por la columna 'Sexo', calcula la suma de la columna 'Peso' para cada grupo y restablece los índices del resultado para obtener un nuevo DataFrame llamado pesos_por_sexo.
pesos_por_sexo

        Sexo   Peso
0   Femenino   55.0
1  Masculino  145.0

In [35]:
estadisticas_por_sexo = df_personas.groupby('Sexo')['Peso'].agg(Media='mean', Suma='sum', Cuenta='count').reset_index() # Agrupa el DataFrame df_personas por la columna 'Sexo', calcula la media, la suma y el conteo de la columna 'Peso' para cada grupo y restablece los índices del resultado para obtener un nuevo DataFrame llamado estadisticas_por_sexo.
estadisticas_por_sexo

        Sexo  Media   Suma  Cuenta
0   Femenino   55.0   55.0       1
1  Masculino   72.5  145.0       2

Ordenaciones

In [37]:
df_personas_ordenado = df_personas.sort_values(by='Edad', ascending=False).reset_index(drop=True) # Ordena el DataFrame df_personas por la columna 'Edad' en orden descendente y guarda el resultado en un nuevo DataFrame llamado df_personas_ordenado.
df_personas_ordenado.head()

    Nombre  Edad    Ciudad       Sexo  Altura  Peso  Alto_booleano Alto_texto
0     Dani  45.0    Bilbao  Masculino   185.0  75.0           True         Sí
1     Fran  40.0   Sevilla        NaN   170.0  60.0          False         No
2      Bob  30.0       NaN  Masculino     NaN  70.0          False         No
3    Alice  25.0    Madrid   Femenino   165.0  55.0          False         No
4  Charlie   NaN  Valencia  Masculino   175.0   NaN          False         No

In [38]:
df_ordenado_multiple = df_personas.sort_values(by=['Nombre', 'Ciudad'], ascending=[True, False]).reset_index(drop=True) # Ordena el DataFrame df_personas por la columna 'Sexo' en orden ascendente y luego por la columna 'Edad' en orden descendente, y guarda el resultado en un nuevo DataFrame llamado df_ordenado_multiple.
df_ordenado_multiple.head()

    Nombre  Edad    Ciudad       Sexo  Altura  Peso  Alto_booleano Alto_texto
0    Alice  25.0    Madrid   Femenino   165.0  55.0          False         No
1      Bob  30.0       NaN  Masculino     NaN  70.0          False         No
2  Charlie   NaN  Valencia  Masculino   175.0   NaN          False         No
3     Dani  45.0    Bilbao  Masculino   185.0  75.0           True         Sí
4     Fran  40.0   Sevilla        NaN   170.0  60.0          False         No

Transponer un Dataframe

In [41]:
df_personas_transpuesto = df_personas.T # Transpone el DataFrame df_personas, intercambiando filas por columnas, y guarda el resultado en un nuevo DataFrame llamado df_personas_transpuesto.
df_personas_transpuesto

                      0          1          2        3          4
Nombre            Alice        Bob    Charlie     Fran       Dani
Edad               25.0       30.0        NaN     40.0       45.0
Ciudad           Madrid        NaN   Valencia  Sevilla     Bilbao
Sexo           Femenino  Masculino  Masculino      NaN  Masculino
Altura            165.0        NaN      175.0    170.0      185.0
Peso               55.0       70.0        NaN     60.0       75.0
Alto_booleano     False      False      False    False       True
Alto_texto           No         No         No       No         Sí